-- MySQL Script generated by MySQL Workbench
-- 09/24/16 13:53:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pulsiraj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pulsiraj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pulsiraj` DEFAULT CHARACTER SET utf8 ;
USE `pulsiraj` ;

-- -----------------------------------------------------
-- Table `pulsiraj`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pulsiraj`.`User` ;

CREATE TABLE IF NOT EXISTS `pulsiraj`.`User` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password_salt` BINARY(32) NOT NULL,
  `random_salt` BINARY(32) NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `approval_status` TINYINT(1) NOT NULL,
  `user_type` ENUM('legal', 'physical') NOT NULL,
  `Usercol` VARCHAR(45) NULL,
  PRIMARY KEY (`u_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pulsiraj`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pulsiraj`.`city` ;

CREATE TABLE IF NOT EXISTS `pulsiraj`.`city` (
  `c_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pulsiraj`.`Municipality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pulsiraj`.`Municipality` ;

CREATE TABLE IF NOT EXISTS `pulsiraj`.`Municipality` (
  `m_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`m_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pulsiraj`.`LegalEntity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pulsiraj`.`LegalEntity` ;

CREATE TABLE IF NOT EXISTS `pulsiraj`.`LegalEntity` (
  `u_id` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `m_id` INT NOT NULL,
  `c_id` INT NOT NULL,
  `land_phone1` VARCHAR(15) NULL,
  `land_phone2` VARCHAR(15) NULL,
  `mobile_phone1` VARCHAR(15) NULL,
  `mobile_phone2` VARCHAR(15) NULL,
  `website` VARCHAR(45) NULL,
  `facebook_profile` VARCHAR(45) NULL,
  `instagram_profile` VARCHAR(45) NULL,
  `open_time` TIME NOT NULL,
  `close_time` TIME NOT NULL,
  PRIMARY KEY (`u_id`),
  INDEX `fk_LegalEntity_City_idx` (`c_id` ASC),
  INDEX `fk_LegalEntity_Municipality_idx` (`m_id` ASC),
  CONSTRAINT `fk_LegalEntity_User`
    FOREIGN KEY (`u_id`)
    REFERENCES `pulsiraj`.`User` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LegalEntity_City`
    FOREIGN KEY (`c_id`)
    REFERENCES `pulsiraj`.`city` (`c_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LegalEntity_Municipality`
    FOREIGN KEY (`m_id`)
    REFERENCES `pulsiraj`.`Municipality` (`m_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pulsiraj`.`PhysicalEntity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pulsiraj`.`PhysicalEntity` ;

CREATE TABLE IF NOT EXISTS `pulsiraj`.`PhysicalEntity` (
  `u_id` INT NOT NULL,
  `first_name` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(25) NOT NULL,
  `gender` ENUM('male', 'female') NOT NULL,
  `dob` DATE NOT NULL,
  `c_id` INT NOT NULL,
  `mobile_phone` VARCHAR(15) NOT NULL,
  `image_url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`u_id`),
  INDEX `fk_PhysicalEntity_City_idx` (`c_id` ASC),
  CONSTRAINT `fk_PhysicalEntity_User1`
    FOREIGN KEY (`u_id`)
    REFERENCES `pulsiraj`.`User` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PhysicalEntity_City`
    FOREIGN KEY (`c_id`)
    REFERENCES `pulsiraj`.`city` (`c_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pulsiraj`.`Sport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pulsiraj`.`Sport` ;

CREATE TABLE IF NOT EXISTS `pulsiraj`.`Sport` (
  `s_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`s_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pulsiraj`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pulsiraj`.`category` ;

CREATE TABLE IF NOT EXISTS `pulsiraj`.`category` (
  `ctg_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ctg_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
